### ISSUE TITLE
Documentation for mseedindex compilation on windows 10 is unclear.

### ISSUE THREAD

**Issue by timronan** [iris-edu/mseedindex#5]
To the best of my knowledge, a nmake executable is no longer available through Visual Studio 2017 (version used for Windows 10). The installation messaging should be updated to prompt user to use the make.exe that can be downloaded as a part of Cygwin, and to update the System path to point directly to the Cygwin bin file. This has other added benefits. On a windows prompt the command must be run as `make WITHOUTPOSTGRESQL=1`

**Comment by chad-earthscope** [comment]
That is incorrect.  Nmake exists for both VS 2017 and 2019.  I do not think it comes with a default install so it may need to be added post-install, but it's there.
