### ISSUE TITLE
leap seconds file

### ISSUE THREAD

**Issue by crotwell** [iris-edu/mseedindex#9]
Instructions here:
https://github.com/EarthScope/mseedindex/blob/main/doc/mseedindex.md
say to get leap seconds file from
https://www.ietf.org/timezones/data/leap-seconds.list
but this link says:
`ietf.org is no longer serving this file.`

**Comment by chad-earthscope** [comment]
Fixed in 123264db9c1e9478929bd74311958d2662bbecd1 to be included in next release.
